export const OPEN_PRODUCT_MODAL = "OPEN_PRODUCT_MODAL";
export const CLOSE_PRODUCT_MODAL = "CLOSE_PRODUCT_MODAL";
export const SET_PRODUCT_MODAL_DATA = "SET_PRODUCT_MODAL_DATA";
export const ADD_CONFIRM_ORDER_DATA = "ADD_CONFIRM_ORDER_DATA";
export const OPEN_FLASH_MESSAGE = "OPEN_FLASH_MESSAGE";
export const CLOSE_FLASH_MESSAGE = "CLOSE_FLASH_MESSAGE";
export const SET_BUSSINESS_DATA = "SET_BUSSINESS_DATA";